name: hipp
channels:
  - conda-forge
dependencies:
  - python=3.10
  - bokeh
  - datashader
  - geopandas
  - holoviews
  - hvplot
  - opencv
  - pandas
  - panel
  - rasterio
  - scikit-image
  - xarray

