name: hipp
channels:
  - conda-forge
dependencies:
  - python=3.10
  - bokeh
  - datashader
  - geopandas
  - holoviews
  - hvplot
  - opencv
  - pandas=1.5.2
  - panel
  - rasterio
  - scikit-image
  - xarray=0.19.0
  - matplotlib=3.5.1

